### PR TITLE
Adding onClose in props

### PR DESCRIPTION
**Pull request by lchuiton**
Hi,

I was losing the call to onClose when closing the calendar after the first time. I managed to make it work by adding the function onClose in the props.

What do you think about it ? 

Thanks.

### CODE REVIEW

**Comment by jacobmischka** [comment]
Hm, it's a difficult question, because it's hard to decide which options should be allowed to be specified as a prop. Right now only `onChange` can be passed as a prop, the rest of flatpickr options need to be passed in the `options` object. I'm not necessarily against this change, but then it raises questions like "Why can `onClose` be passed as a prop but not `onOpen`?".

I think either we should keep it as it currently is, where only `onChange` is a prop and the rest must go in `options`, or allow any flatpickr option to be specified as a prop. The former is simpler, so I think we should stick with that.

Did you try passing `onClose` to the `options` property object? That should work instead. So something like this:

```jsx
<Flatpickr options={{onClose: function(dates) { console.log(dates); }} />
```

**Comment by jacobmischka** [comment]
Oops, I didn't mean to close this just yet.

**Comment by lchuiton** [comment]
I first tried to use `onClose` by adding it in the `options` object, but I had this behavior of being able to have `onClose` called only once. When the calendar is closed the first time, I'm triggering an action and after that, the `onClose` method is never called again when I'm using the calendar.

That's why I made this modification of passing `onClose` directly in props, as it is, like `onChange`, define as a hook in `flatpickr`.
But I can't find the reason why it's working this way and not with `onClose` being declared in `options` ...

**Comment by jacobmischka** [comment]
Oh, I see the problem. I'm going to merge this to recognize your contribution, but I'm going to rewrite it immediately because I need to fix the other hooks too.

Thanks for pointing this out!

**Comment by jacobmischka** [comment]
Should be fixed in `3.3.0`, added a new example to `examples`. All hooks can now be passed as a prop, and will also correctly work if passed as an option. You can do it either way now and it should work.

Thanks again!

**Pull request merged**
